/// Flutter icons MyBus
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
//  fonts:
//   - family:  MyBus
//     fonts:
//      - asset: fonts/MyBus.ttf
///
///
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyBus {
  MyBus._();

  static const _kFontFam = 'MyBus';
  static const String? _kFontPkg = null;

  static const IconData shippingFast =
      IconData(0xf48b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
